### ISSUE TITLE
Valparaíso's Flag (Chile)

### ISSUE THREAD

**Issue by cuinuhekqkd** [stadust/pointercrate#111]
![3](https://github.com/stadust/pointercrate/assets/166937464/38b525fd-15e7-4a5d-95ac-b1752d614ff4)

**Country**: Chile"
**Subdivision**: Valparaíso
**ISO-Code**: CL-VA
**Link to PUBLIC DOMAIN `.svg` of flag**: <https://es.wikipedia.org/wiki/Archivo:Flag_of_Valparaiso_Region,_Chile.svg

**Comment by stadust** [comment]
Hi @cuinuhekqkd,
that flag is sadly not public domain, but rather GFDL licencsd. GFDL is a copy-left license, which makes it incompatible with pointercrate's MIT license, so we cannot use this flag :(
