### ISSUE TITLE
Flag Los Lagos, Chile

### ISSUE THREAD

**Issue by mast3rn** [stadust/pointercrate#112]
Country: Chile
Subdivision: Los Lagos
ISO-Code: CL-LL
Link to PUBLIC DOMAIN .svg of flag: https://commons.m.wikimedia.org/wiki/File:Flag_of_Los_Lagos_Region,_Chile.svg#mw-jump-to-license

**Comment by exsii** [comment]
it's not public domain
don't use wikimedia commons for flags marked as TBA

**Comment by stadust** [comment]
Hi @mast3rn,
As @exsii mentions, that flag is not public domain, but rather GFDL licenced. GFDL is a copy-left license, which makes it incompatible with pointercrate's MIT license, so we cannot use this flag :(
