### ISSUE TITLE
[FLAGS]

### ISSUE THREAD

**Issue by gt0run** [stadust/pointercrate#114]
Please add the following missing flag to the pointercrate stats viewer:

**Country**: 
**Subdivision**: 
**ISO-Code**: 
**Link to PUBLIC DOMAIN `.svg` of flag**: 

Thanks

**Comment by stadust** [comment]
Hi @gt0run,
It looks like you forgot to fill in the template :(

**Comment by stadust** [comment]
Hi @gt0run, 
I'm closing this, but please feel free to reopen once you filled out the template :)
