### ISSUE TITLE
[Córdoba Flag]

### ISSUE THREAD

**Issue by HipoSmokeWeed** [stadust/pointercrate#128]
Please REPLACE the following flag to the pointercrate stats viewer:

**Country**: Argentina 
**Subdivision**: Córdoba 
**ISO-Code**: AR-X 
**Link to PUBLIC DOMAIN `.svg` of flag**: https://cdn.discordapp.com/attachments/606610501409046533/1235324834339225800/cordoba.svg?ex=6633f567&is=6632a3e7&hm=45dbdb97b575c5e31a83920f34ccf48a5da17c4c283917b9ac0f3cd1f87ef917& 

NOTE: This is self-drawn. To whoever is reading this, you can ask exsii to confirm that it is indeed 100% self-drawn. I'm requesting this flag because the current Córdoba flag in the site (and most if not all of the argentina's subdivisions flags) is wrong (pretty sure it's a WAYYYY older version).

Thanks

**Comment by stadust** [comment]
Hi, thanks for the request. Sadly, we cannot accept self-drawn flags, because we have no way to verify they are actually self-drawn.
