### ISSUE TITLE
Search in nations stat viewer is case sensitive

### ISSUE THREAD

**Issue by FiNiTe-Weeb** [stadust/pointercrate#144]
So, the player search works fine:
![image](https://github.com/stadust/pointercrate/assets/101021772/02e3d165-9a6a-4f4e-96e6-ad52cf7c3c5a)

BUT the nation search is case sensitive:
![image](https://github.com/stadust/pointercrate/assets/101021772/37c2738c-0e97-4679-a4e8-0714b2c51d16)
![image](https://github.com/stadust/pointercrate/assets/101021772/7382c583-4d34-4f51-9386-cdc041026c35)

**Comment by stadust** [comment]
Yep, that should indeed not be case sensitive
