### ISSUE TITLE
Time Machine should default to today's date, not 1971

### ISSUE THREAD

**Issue by stadust** [stadust/pointercrate#152]
Currently the datetime selector always defaults to 19-06-1971, which is a placeholder value I used during development and apparently forgot to replace with proper logic that would initialize it to the current date (e.g. the day at which the website is being viewed)

**Comment by AbhisekLucky** [comment]
getdate()

**Comment by emonadeo** [comment]
`new Date()`, actually

**Comment by stadust** [comment]
Neither, the default is set server sided

**Comment by emonadeo** [comment]
💀

**Comment by stadust** [comment]
fixed by https://github.com/stadust/pointercrate/pull/168
