### ISSUE TITLE
Nation stats viewer is broken

### ISSUE THREAD

**Issue by romandaher** [stadust/pointercrate#156]
Clicking on one of the countries in https://pointercrate.com/demonlist/statsviewer/nations/ gives a 500 error

To reproduce error:
Make a request to 
https://pointercrate.com/api/v1/nationalities/(any country code)
get a 500 error

**Comment by romandaher** [comment]
I also don't know if this is intentional, but https://pointercrate.com/documentation/nationalities has no documentation about that endpoint.

**Comment by stadust** [comment]
Hi @romandaher, 
thanks for the report. I have just pushed a fix for this, which will be deployed momentarily

**Comment by stadust** [comment]
> I also don't know if this is intentional, but https://pointercrate.com/documentation/nationalities has no documentation about that endpoint.

This is indeed intentional, the API in question is considered unstable and internal only

**Comment by stadust** [comment]
> Hi @romandaher, thanks for the report. I have just pushed a fix for this, which will be deployed momentarily

Deployment went through, and the nation stats viewer is working again. Thanks again for the report!
