### ISSUE TITLE
Work out URL questions for demonlist

### ISSUE THREAD

**Issue by stadust** [stadust/pointercrate#19]
Related to #9 and #2 

we'll want to keep the /demonlist/<position>/ thingy but add something to get demons by id and, probably /demons/<demon id>/

idk how to feel about allowing urls to work with demon names again, so I'm keeping the wont fix on that issue for now

**Comment by stadust** [comment]
There are way to permalink by id now, with the endpoint being a redirect to the position links

**Comment by bennyd87708** [comment]
Sorry to reopen this, but what is the format to permalink by ID? I tried /demonlist/[ID] and /demons/[ID] to no avail

**Comment by kyurime** [comment]
On the list you can click here to copy the permalink
![image](https://user-images.githubusercontent.com/25387744/119074471-f53aa080-b9a3-11eb-9e5c-c7a5711e168b.png)
(wow there should really be a visual indicator of a copy/a grab pointer here lol)
Doing so will reveal that the format is actually
`/demonlist/permalink/<id>`
