### ISSUE TITLE
Create endpoint for retrieving linked player of logged in user

### ISSUE THREAD

**Issue by stadust** [stadust/pointercrate#191]
Currently, there's no programmatic way to get the player object that's claimed by the logged in user. There is `GET /api/v1/claims` which allows filtering, but its restricted to moderators. The frontend currently simply queries the database directly when building the HTML server sided.

Some considerations:
- This cannot be part of the `/api/v1/auth/me` endpoint, because that endpoint lives in `pointercrate-user-api`, but player claim info lives in `pointercrate-demonlist` (and a dependency from user on demonlist is neither possible nor wanted)
- If we add some subendpoint like `/api/v1/auth/me/claimed`, we might want to consider if there's ever gonna be a need for more information like this, and whether we might want something more general like `/api/v1/auth/me/demonlist_integrations` which can be extended later.

**Comment by Gunner-Bones** [comment]
hi
