### ISSUE TITLE
Use of internal Diesel APIs likely to break in 2.0

### ISSUE THREAD

**Issue by sgrif** [stadust/pointercrate#30]
o/

I'm investigating the potential breakage of a soon-to-be-opened PR for Diesel 2.0 and I found your crate. We're making some changes to how aggregation is handled to support `GROUP BY`, which is going to lead to an additional bound on `impl SelectDsl for SelectStatement`. Previously our aggregation handling was implied by `T: SelectableExpression<QS>`, but that's because 1.0 doesn't actually check it very much, and we check it incorrectly since the answer to "Is users.name aggregate?" changes based on the group by clause.

Anyway I'm getting way too sidetracked on implementation details. The important thing is that based on a cursory look over the code which is going to break (https://github.com/stadust/pointercrate/blob/61168074c90fd62140369af2b88cd348959d6c3d/src/model/mod.rs#L46-L55), the only reason you'll be affected by breakage is because you're depending on internal APIs! Luckily this means that you can make your code forwards-compatible by changing it to only use public API.

`SelectStatement` and `BoxedSelectStatement` are both internal APIs (ironically, `BoxedDsl::internal_into_boxed` is not an internal API. We should probably rename it, except it's public API so...). Diesel's definition of "public API" is "Appears in the documentation at docs.diesel.rs". While we try to use Rust's privacy mechanisms whenever possible, ultimately a lot of important code gets generated by macros we export. That means that we need to make certain functions/types public from Rust's point of view, but private from a semver point of view. For example, `SelectStatement::simple`, which you're using, only exists to be called from code generated by `table!`, but we never intended for users to directly rely on it.

The result of this is that a lot of your trait bounds are based on those from things considered internal to Diesel. You should try to only use the bounds from the functions you're directly calling, which will also have the nice side effect of making your code smaller. What you ultimately need is something like this:

```rust
trait Model {
    type From: QueryDsl + SelectDsl<Self::Selection>
    type Selection: Expression;

    fn from() -> Self::From; // unchanged
    fn selection() -> Self::Selection; // unchanged

    fn all() -> Select<Self::From, Self::Selection> {
        Self::from().select(Self::Selection)
    }

    fn boxed_all<'a>() -> IntoBoxed<'a, Select<Self::From, Self::Selection>, Pg>
    where
        Select<Self::From, Self::Selection>: BoxedDsl<'a, Pg>,
    {
        Self::all().into_boxed()
    }
}
```

You may need to break that into two traits to avoid the method level where clause on `boxed_all`. I unfortunately don't have time to open a PR, but hopefully this helps. In the event that the change proposed above can't work for you, adding a `NonAggregate` bound to `Model::Selection` should also insulate you. If that isn't suitable, adding `ValidGrouping<()>` will work, but isn't forwards compatible and what the exact bound will be may change by the time 2.0 comes out.

While I've written a lot here, it's mostly because I'd like to see you decoupled from our internals. Aside from that, this will likely be the only breakage that affects you, and the minimum required change shouldn't be a big issue. We'll be doing an RC before the final release next year, and I'd love to get your feedback on if the migration was easy (if it's not we need to fix that). Let me know if you have any questions on this

**Comment by stadust** [comment]
Hey! )/

Thanks for the heads-up, that's quite some service :D

Most of that trait was written in a rustc induced rage because the error messages when getting diesel types wrong only slightly are truly horrendous. I ended up copying things together directly from the diesel source, which is how I ended up with code normally only generated by the `table!` macro (and I think back when i wrote it I was still doing JOINs in rust code instead of database views, so `From` wasn't always a table. Though I guess that shouldn't make a difference really, now that I'm thinking about it). So yeah, I messed up quite a lot.

Fixing it with what you wrote was pretty straightforward though, so thank you very much!
