### ISSUE TITLE
stats viewer names not updating when clicking on others

### ISSUE THREAD

**Issue by wpoiw** [stadust/pointercrate#34]
this seems to occur when clicking on names with no nationality, the name and nationality remain as those of the previous person (or blank if no one was selected prior)

![image](https://user-images.githubusercontent.com/41485054/80255071-25feb800-8674-11ea-9e15-29574662d43c.png)
![image](https://user-images.githubusercontent.com/41485054/80255104-30b94d00-8674-11ea-958f-267c70b238fa.png)
![image](https://user-images.githubusercontent.com/41485054/80255168-4f1f4880-8674-11ea-8c82-fa3420540c04.png)

**Comment by stadust** [comment]
Hi!

I for some reason have not received an e-mail about this, so sorry for my delayed response :(
Thanks for bringing this to my attention though!

This must be related to all the changes to the JS code I did in march, I'll work on fixing it this evening.

**Comment by zmxhawrhbg** [comment]
Since this doesn't seem fixed yet -
Replace `.innerHTML` with `.textContent` in 
https://github.com/stadust/pointercrate/blob/fdfd7140aed2a20894ef526af820dedf4991378b/static2/js/modules/demonlist.mjs#L109

**Comment by stadust** [comment]
Looks reasonable, PR? :D

I'm drowning in classwork rn >.>
