### ISSUE TITLE
list demons created/published/verified links go to the wrong levels

### ISSUE THREAD

**Issue by wpoiw** [stadust/pointercrate#35]
clickable level links in a player's list demons created/published/verified link to the wrong demon pages

for example, in nSwish's list demons verified, "cognition" wrongfully links to "wander of thought"

![image](https://user-images.githubusercontent.com/41485054/81354233-fb285100-90c2-11ea-8bf1-0a9aa3f2efd6.png)
![image](https://user-images.githubusercontent.com/41485054/81354020-763d3780-90c2-11ea-99b0-e7bf23b5934e.png)
(should link to /demonlist/6/)

**Comment by stadust** [comment]
aw man, I must have switched up IDs and positions somewhere

**Comment by stadust** [comment]
Problem's in this line, should be `demon.position`, not `demon.id`
https://github.com/stadust/pointercrate/blob/b69a035ae871e0165c90b722fb6471b9f33274ff/static2/js/modules/demonlist.mjs#L229

**Comment by stadust** [comment]
Closed by #37
