### ISSUE TITLE
empty descriptions show up as "" when viewing demons

### ISSUE THREAD

**Issue by ghost** [stadust/pointercrate#38]
while technically not wrong as present descriptions go within the quotation marks, it does look annoying and weird
![image](https://user-images.githubusercontent.com/41485054/82163301-31738680-98a2-11ea-95ca-32cd369b4de8.png)

**Comment by stadust** [comment]
That entire subsystem is broken at the moment, once I get the time to rework the whole GD integration, I'll fix this as well ig (dont expect anything before december though)

**Comment by stadust** [comment]
Seems to be fixed since switch to dash-rs for GD integration
