### ISSUE TITLE
Does Pointercrate has an official app?

### ISSUE THREAD

**Issue by acceler8tion** [stadust/pointercrate#47]
I would like to create an app for pointercrate(unofficial) that runs on the **Android**. 
Before that, I wonder if there is an official app that exists.

**Comment by stadust** [comment]
No such app exists, and no development of one is planned from our side

**Comment by acceler8tion** [comment]
Can I make a daemonist app using Pointercrate API? absolutely unofficial

**Comment by stadust** [comment]
Sure, though keep in mind that there are part of the website that cannot be replicated via the API (and the API docs arent exactly up to date rn >.>)
