### ISSUE TITLE
Do not work `position` field

### ISSUE THREAD

**Issue by acceler8tion** [stadust/pointercrate#48]
I tried filtering using a '**position**' field *(in many situations)*, but it doesn't work at all.

> `api/v1/demons/?position=10`
> **Normal** - returns no.10 demon
> **Output** - returns no.1\~no.50 demonlist

</br>

> `api/v1/demons/?limit=10&position__gt=10`
> **Normal** - returns no.11\~no.20 demonlist
> **Output** - returns no.1\~no.10 demonlist

To put the proper analogy, it's the same effect as none.

**Comment by stadust** [comment]
Documentation error, that field is not actually supported on that endpoint.

use `/api/v2/demons/` for pagination by `id` and `/api/v2/demons/listed/` for pagination of placed demons by position

**Comment by acceler8tion** [comment]
Oh, I see! By the way, when are you planning to support for the position field

**Comment by stadust** [comment]
Not at all. See https://pointercrate.com/documentation/index/#pagination, https://pointercrate.com/documentation/demons/#demon-listing and https://pointercrate.com/documentation/demons/#demon-retrieval
