### ISSUE TITLE
POST /api/v1/records/ with status=approved causes 42800 error

### ISSUE THREAD

**Issue by stadust** [stadust/pointercrate#5]
42800 is PRECONDITION REQUIRED. I have no idea why this happens. `status=submitted` works fine

**Comment by Zmxhawrhbg** [comment]
Hi, I had homework so I looked into this and here is my initial idea:
https://github.com/stadust/pointercrate/blob/828ad7b9d3c555f74c1ca5db443ff12959b6a1a8/src/model/record/post.rs#L158-L166
When there's a duplicate submission with a lower progress, the `record.delete` function is called with the current context.
However, the thing about the `record.delete` function is that it not only requires list perms, but an ETag to be submitted as shown here
https://github.com/stadust/pointercrate/blob/828ad7b9d3c555f74c1ca5db443ff12959b6a1a8/src/model/record/delete.rs#L10-L11
My guess is that if the context doesn't give list perms, then it just fails silently. As should be noted, if `status=submitted`, the first line (check perms) is run, but not the second (check ETag), and the records aren't deleted from the database.
A possible solution may be to get the ETag and put it into the context before sending it to the delete function, but this doesn't solve how it fails silently if the user doesn't have the correct permissions.

**Comment by stadust** [comment]
Ahhh yes, this is it, thanks! Nice work :D

I gotta use an `RequestContext::Internal` variant there. All permission checks have already been done before, so a context that grants blanko-pass to all checks is safe to use here (and required as we can see)
