### ISSUE TITLE
Confusing Grammar Point

### ISSUE THREAD

**Issue by PersonHuamn42** [stadust/pointercrate#55]
I was checking the status of my submission to the list, and it told me "_This record has already been under consideration_". This made me think that it had been denied, due to the _has already been_. However, looking at the error codes of "_The record has already been approved/rejected/submitted/approved_", it makes me think that the record is under consideration, but due to the template used of "The record has already been x", it appears it has been denied. If I'm wrong, and it has simply been rejected, I apologise for wasting your time.

**Comment by stadust** [comment]
Fixed in the rewrite, the error message uses present tense now!
