### ISSUE TITLE
Web: Footer Text Is Incredibly Small

### ISSUE THREAD

**Issue by jessiejs** [stadust/pointercrate#73]
The footer text in [Pointercrate](https://pointercrate.com/) is tiny.
Changing the size from 0.5em to 1em makes it more readable, but that looks kinda silly due to how much the lines wrap, but that can be fixed by either increasing, or completely removing the max-width from the sections.

**Comment by stadust** [comment]
Making the text bigger and relaxing the column width seems reasonable to me. One thing to keep in mind is how the footer renders on mobile, though

**Comment by stadust** [comment]
Fixed by #120
