### ISSUE TITLE
Lock submissions cannot be overwritten by Moderator+

### ISSUE THREAD

**Issue by vulcanium4** [stadust/pointercrate#80]
Currently nobody can override lock submissions which makes it difficult to reorder submission orders.

**Comment by stadust** [comment]
The check for this is here: https://github.com/stadust/pointercrate/blob/a3683bdab3c028398e5b702079df1570fd943782/pointercrate-demonlist-api/src/endpoints/record.rs#L126-L134
It should be a simple case of extending the inner `if` statement with `&& !is_team_member`

**Comment by stadust** [comment]
Since the core problem leading to this ask will be addressed by #154, I am closing this issue as "not planned"
