### ISSUE TITLE
Add more countries for Political Subdivisions

### ISSUE THREAD

**Issue by rmAlt1** [stadust/pointercrate#85]
Add political subdivision to another large countries (like France, Germany, Spain, Russia, etc.)

**Comment by exsii** [comment]
if you really wanted to, you could've added subdivisions yourself by modifying the world map's .svg file at pointercrate-demonlist-pages/static/images/world.svg
new regions are being worked on rn though

**Comment by shikoshib** [comment]
> if you really wanted to, you could've added subdivisions yourself by modifying the world map's .svg file at pointercrate-demonlist-pages/static/images/world.svg, as well as adding needed subdivision flags in /images/flags new regions are being worked on rn though, i will finish this month 100%

that would be cool, gl
(привет)
